
export interface UserProfile {
  id: string;
  user_id: string;
  first_name: string;
  last_name: string;
  email: string;
  application_status: string;
  credentials: string;
  birth_day?: string;
  gov_id_number?: string;
  gov_id_image?: string;
  cpu_type?: string;
  ram_amount?: string;
  has_headset?: boolean;
  has_quiet_place?: boolean;
  speed_test?: string;
  system_settings?: string;
  available_hours?: string[];
  available_days?: string[];
  day_hours?: Record<string, any>;
  sales_experience?: boolean;
  sales_months?: string;
  sales_company?: string;
  sales_product?: string;
  service_experience?: boolean;
  service_months?: string;
  service_company?: string;
  service_product?: string;
  meet_obligation?: boolean;
  login_discord?: boolean;
  check_emails?: boolean;
  solve_problems?: boolean;
  complete_training?: boolean;
  personal_statement?: string;
  accepted_terms?: boolean;
  agent_id?: string;
  agent_standing?: string;
  lead_source?: string;
  supervisor_notes?: string;
  start_date?: string;
}
